name: Build and Deploy to GCloud
on:
  push:
    branches:
      - 'chore/docker-on-github-actions'
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: elixir:1.9.1-slim
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: github_actor
          POSTGRES_DB: stonex_test
          POSTGRES_PASSWORD: "@postgresPwd"
        ports:
          - 5432/tcp
    steps:
    - uses: actions/checkout@v1
    - name: Configure Project Secrets
      run: |
        cp ./config/sample.secret.exs ./config/dev.secret.exs
        cp ./config/sample.secret.exs ./config/test.secret.exs
        sed -i 's/"username"/"github_actor"/g' ./config/test.secret.exs
        sed -i 's/"password"/"@postgresPwd"/g' ./config/test.secret.exs
        sed -i 's/"database"/"stonex_test"/g' ./config/test.secret.exs
        sed -i 's/"hostname"/"postgres"/g' ./config/test.secret.exs
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
      env:
        MIX_ENV: test
    - name: Check code Format
      run: mix format --check-formatted --dry-run
      env:
        MIX_ENV: test
    - name: Run code Analysis
      run: mix credo
      env:
        MIX_ENV: test
    - name: Setup Database
      run: |
        mix ecto.create
        mix ecto.migrate
      env:
        MIX_ENV: test
    - name: Run Tests
      run: mix test
      env:
        MIX_ENV: test
  build_and_deploy:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: google/cloud-sdk
    steps:
    - uses: actions/checkout@v1
    - name: Setup Google Cloud SDK
      run: |
        echo '${{ secrets.GOOGLE_SERVICE_KEY }}' > /tmp/gcloud-service-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcloud-service-key.json
        gcloud --quiet config set project personal-231922
        gcloud --quiet config set compute/zone us-central1
        gcloud auth configure-docker
    - name: Configure Project Secrets
      run: |
        cp ./config/sample.secret.exs ./config/dev.secret.exs
        cp ./config/sample.secret.exs ./config/test.secret.exs
    - name: Build Docker Image
      run: |
        docker build \
        --build-arg DATABASE_URL=${{ secrets.PROD_DATABASE_URL }} \
        --build-arg SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} \
        --build-arg POOL_SIZE=5 \
        -t gcr.io/personal-231922/stonex/app:latest .
    - name: Deploy Image to Google Cloud
      run: docker push gcr.io/personal-231922/stonex/app:latest
