name: Build and Deploy to GCloud
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/cloud-sdk
    steps:
    - uses: actions/checkout@v1
    - name: Setup Google Cloud SDK
      run: |
        echo '${{ secrets.GOOGLE_SERVICE_KEY }}' > /tmp/gcloud-service-key.json
        gcloud auth activate-service-account --key-file=/tmp/gcloud-service-key.json
        gcloud --quiet config set project personal-231922
        gcloud --quiet config set compute/zone us-central1
        gcloud auth configure-docker
    - name: Configure Project Secrets
      run: |
        cp ./config/sample.secret.exs ./config/dev.secret.exs
        cp ./config/sample.secret.exs ./config/test.secret.exs
    - name: Build Docker Image
      run: |
        docker build \
        --build-arg DATABASE_URL=${{ secrets.PROD_DATABASE_URL }} \
        --build-arg SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} \
        --build-arg POOL_SIZE=5 \
        -t gcr.io/personal-231922/stonex/app:latest .
    - name: Deploy Image to Google Cloud
      run: docker push gcr.io/personal-231922/stonex/app:latest
