name: Build and Deploy to GCloud
on:
  push:
    branches:
      - 'chore/docker-on-github-actions'
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: google/cloud-sdk
    steps:
    - uses: actions/checkout@v1
    - name: Setup Google Cloud SDK
      run: |
        echo "0"
        echo "1"
        echo '${{ secrets.GOOGLE_SERVICE_KEY }}' > /tmp/gcloud-service-key.json
        echo "1.5"
        cat /tmp/gcloud-service-key.json
        echo "2"
        gcloud auth activate-service-account --key-file=/tmp/gcloud-service-key.json
        echo "3"
        gcloud --quiet config set project personal-231922
        echo "4"
        gcloud --quiet config set compute/zone us-central1
        echo "5"
        gcloud auth configure-docker
        echo "6"
    - name: Build Docker Image
      run: |
        docker build \
        --build-arg DATABASE_URL=${{ secrets.PROD_DATABASE_URL }} \
        --build-arg SECRET_KEY_BASE=${{ secrets.SECRET_KEY_BASE }} \
        --build-arg POOL_SIZE=5 \
        -t gcr.io/personal-231922/stonex/app:latest .
    - name: Deploy Image to Google Cloud
      run: docker push gcr.io/personal-231922/stonex/app:latest
